# Generated by Django 5.0.7 on 2024-10-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_studentlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='user',
        ),
    ]
