# Generated by Django 5.0.7 on 2024-09-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_studentlist'),
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('AOOP', 'Advanced object oriented programming'), ('PFSD', 'Python full stack development'), ('OS', 'Operating system'), ('AIML', 'Artificial Inteligence and Machine learning')], max_length=50)),
                ('section', models.CharField(choices=[('S4', 'Section4'), ('S2', 'Section2'), ('S1', 'Section1'), ('S3', 'Section3')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist')),
            ],
        ),
    ]
