# Generated by Django 5.0.7 on 2024-10-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0005_alter_addcourse_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='section',
            field=models.CharField(choices=[('S1', 'Section 1'), ('S2', 'Section 2'), ('S3', 'Section 3'), ('S4', 'Section 4')], max_length=50),
        ),
    ]
